# GitHub Pages Configurations

remote_theme: nikahmadz/central

title: Central # The title of your site
# description: # A short description about your site
favicon: favicon.ico
# manifest: manifest.json
# color_scheme: 'light dark'
# theme_color: '#202020'

# google_analytics: # Fill in your Google Analytics ID to track your website using Google Analytics

sass: # sass configurations
  style: compressed

exclude: # Exclude these files from production site
- "*.gemspec"
- README.md
- CONTRIBUTING.md
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md

# plugins: # jekyll plugins
#  - jekyll-remote-theme
#  - jekyll-paginate
#  - jekyll-sitemap
